final List<String> generalDares = [
  "Do 100 squats.",
  "Keep your eyes closed until it’s your go again.",
  "Like the first 15 posts on your Facebook newsfeed.",
  "Keep three ice cubes in your mouth until they melt.",
  "Yell out the first word that comes to your mind.",
  "Show the last five people you texted and what the messages said.",
  "Eat a spoonful of mustard.",
  "Put 10 different available liquids into a cup and drink it.",
  "Try to lick your elbow.",
  "Call the first person in your phonebook and howl like a wolf",
  "Try not to laugh for the next 10 minutes",
  "For the next 10 minutes, every time someone asks you something, respond with a bark",
  "Put as many snacks into your mouth at once as you can.",
  "Tell everyone an embarrassing story about yourself.",
  "Post the oldest selfie on your phone on Instagram Stories.",
  "For a guy, put on makeup. For a girl, wash off your make-up.",
  "Do four cartwheels in a row.",
  "Tell the saddest story you know.",
  "Give a personalised insult to everyone in the room",
  "Howl like a wolf.",
  "Dance without music for one minute.",
  "Eat five tablespoons of a condiment.",
  "Break two eggs on your head.",
  "Attempt to walk on your hands for as far as you can.",
  "Try to juggle 2 or 3 items of the group’s choosing.",
  "Imitate a celebrity every time you talk.",
  "Hold a funny face for the rest of the round.",
  "Open a bag of snacks or candy using only your mouth, no hands or feet.",
  "Act like whatever animal someone yells out for the next 1 minute.",
  "Sit in a spinning chair and have the group spin you for 30 seconds.",
  "Jump up and down as high as you can go for a full minute.",
  "Let two people give you a wet willy at the same time.",
  "Sing a praise song about a person of the groups choosing.",
  "Stick your arm into the trash can past your elbow.",
  "Let the group pose you in an embarrassing position and take a picture.",
  "Let the group look through your phone for one minute.",
  "Let the person to your left draw on your face with a pen.",
  "Imitate popular YouTube videos until someone can guess the video you are imitating.",
  "Grab a trash can and make a hoop with your hands above the trash can. ",
  "Have other members of the group try to shoot trash through your hoop.",
  "Update your relationship status to ‘engaged’ on Facebook",
  "Do pushups until you can’t do any more, wait 5 seconds, and then do one more.",
];
final List<String> goodDare = [
  "Show the most embarrassing photo on your phone.",
  "Twerk for a minute.",
  "Empty out your wallet/purse and show everyone what’s inside.",
  "Try to put your whole fist in your mouth.",
  "Remove four items of clothing.",
  "Eat a raw egg",
  "Be someone’s pet for the next 5 minutes.",
  "Try to drink a glass of water while standing on your hands.",
  "Say two honest things about everyone else in the group.",
  "Try and make the group laugh as quickly as possible.",
  "Belly dance like your life depended on it.",
  "Curse like a sailor for 20 seconds straight.",
  "Serenade the person to your right.",
  "Talk in an accent for the next 3 rounds.",
  "Make every person in the group smile, and keep going until everyone has cracked a smile.",
  "Attempt to do a magic trick.",
  "Attempt to breakdance for one minute.",
  "Do the worm.",
  "Take a shower with your clothes on.",
  "Sell a piece of trash to someone in the group using your best salesmanship.",
  "Gargle something that shouldn’t be gargled, but won’t hurt you.",
  "Spin an imaginary hula hoop around your waist for the rest of the round.",
  "Compose a poem on the spot based on something the group comes up with.",
  "Poll dance for 1 minute with an imaginary pole.",
  "Post an extremely unflattering picture of yourself to the social media outlet of your choosing.",
  "Drag your butt on the carpet like a dog from one end of the room to the other.",
  "Let the person next to you wax you wherever they want",
  "Eat one teaspoon of the spiciest thing you have in the kitchen.",
  "Pretend to be food. Don’t pretend to eat the food, pretend to be the food.",
  " Keep pretending until someone in the group guesses the food you are.",
  "Drop something in the toilet and then reach in to get it.",
  "Dance with no music for 1 minute.",
  "Put ice cubes down your pants.",
  "Lick the floor.",
];

final List<String> funnyDares = [
  "Give a foot massage to the person on your right.",
  "Say something dirty to the person on your left.",
  "Let the rest of the group DM someone from your Instagram account.",
  "Eat a banana without using your hands.",
  "Eat a raw onion.",
  "Give a lap dance to someone of your choice.",
  "Show off your orgasm face.",
  "Do your best impression of a baby being born.",
  "Pretend to be the person to your right for 10 minutes.",
  "Do your best sexy crawl.",
  "Let someone shave part of your body.",
  "Pole dance with an imaginary pole.",
  "Let someone else tickle you and try not to laugh.",
  "Kiss the person to your left.",
  "Let the group give you a new hairstyle.",
  "Get slapped on the face by the person of your choosing.",
  "Seduce a member of the group.",
  "Choose someone from the group to give you a spanking.",
  "Imagine something in your room. Now spell it with your nose and keep spelling it with your nose until someone from the group guesses what you are trying to spell.",
  "After the group chooses one rude word, sing a song and insert that rude word once into every line of the song.",
  "Bend at the waist so that you are looking behind you between your legs. Now run backwards until you can tag someone with your butt.",
  "Go to the bathroom, take off your underwear and put it on your head. Wear it on your head for the rest of the game.",
  "Transfer an ice cube from your mouth to the person’s mouth on your right.",
  "Call the 3rd contact on your phone and sing them 30 seconds of a song that the group chooses.No talking.",
  "Find the person whose first name has the same letter as your first name or whose first name’s the first letter is closest to yours. Now lick their face.",
  "Depict a human life through interpretive dance.",
  "Write something embarrassing somewhere on your body (that can be hidden with clothing) with a permanent marker.",
  "Switch clothes with someone of the opposite sex in the group for three rounds.",
  "Give someone your phone and let them send one text to anyone in your contacts.",
  "Drink a small cup of a concoction that the group makes.",
  "Make up a 30-second opera about a person or people in the group and perform it.",
];
final List<String> generalTruth = [
  "Tell us your most embarrassing vomit story.",
  "If you had to change your name, what would your new first name be?",
  "Would you trade in your pet for a million dollars?",
  "Where was your favourite childhood vacation spot?",
  "What is the most childish thing you still do?",
  "Do you talk in your sleep?",
  "When was the last time you lied?",
  "What’s one silly thing you can’t live without?",
  "How many selfies do you take per day?",
  "What is the most embarrassing picture of you?",
  "What’s the longest you’ve ever spent in the bathroom?",
  "What’s the worst thing you’ve ever done?",
  "What’s the biggest misconception about you?",
  "Do you eat food off the floor?",
  "What’s the worst time you let someone take the blame for something you did?",
  "What do most people think is true about you, but isn’t?",
  "What is the biggest thing you’ve gotten away with?",
  "If you could be a fictional character for a day, who would you choose?",
  "Why did you break up with your last boyfriend or girlfriend?",
  "What is the most embarrassing series of texts you have on your phone?",
  "When was the last time you cried?",
  "Tell me about your first kiss",
  "What is the most embarrassing thing in your room?",
  "Do you have a hidden talent?",
  "What is the stupidest thing you have ever done?",
  "What pictures or videos of you do you wish didn’t exist?",
  " Tell me about your most awkward date.",
  "Are you afraid of the dark?",
  "What is the most expensive thing you have stolen?",
  "Who was your first celebrity crush?",
  "Have you ever cheated in an exam?",
  "What’s the drunkest you’ve ever been?",
  "What is the silliest thing you have an emotional attachment to?",
  "What’s the biggest mistake you’ve ever made?",
  "What’s the most disgusting thing you’ve ever done?",
  "What’s your worst habit?",
  "What is the most useless piece of knowledge you know?",
  "What’s the strangest dream you’ve had?",
  "What’s the most trouble you’ve been in?",
  "What is the scariest dream you have ever had?",
  "If you starred in a romance, what would it be like?",
  "What was the cruellest joke you played on someone?",
  "What is the most embarrassing thing you have put up on social media?",
  "What is the most embarrassing nickname you have ever had?",
  "When was the last time you wiped a booger off on something that shouldn’t have boogers on it?",
];
final List<String> goodTruths = [
  "When was the last time you peed in bed?",
  "What is your deepest darkest fear?",
  "What is something your friends would never expect you do?",
  "What’s the most embarrassing thing you’ve ever done?",
  "Have you ever broken the law?",
  "What is the weirdest trend you’ve ever participated in?",
  "What’s the worst thing you’ve ever said to anyone?",
  "If you could only listen to one song for the rest of your life, what would you choose?",
  "What would you do if you were the opposite sex for a week?",
  "What’s your biggest regret?",
  "What’s something you’re glad your mum doesn’t know about you?",
  "What’s the worst thing anyone’s ever done to you?",
  "Have you ever been caught doing something you shouldn’t have?",
  "Have you ever lied to get out of a bad date?",
  "Have you ever peed in the shower?",
  "Who do you text the most?",
  "Have you ever shit yourself since you were a child?",
  "What is the most embarrassing thing your parents have caught you doing?",
  "What secret about yourself did you tell someone in confidence and then they told a lot of other people?",
  "When was the most inappropriate time you farted?",
  "If you could date a fictional character, who would it be?",
  "What is the grossest thing that has come out of your body?",
  "Who have you loved but they didn’t love you back?",
  "Have you ever been fired from a job?",
  "What is the grossest thing you have had in your mouth?",
  "If you could reincarnate in someone else’s body, who would you want to become?",
  "Have you ever been caught checking someone out? How did they react?",
  "Tell me about the last time someone unexpectedly walked in on you while you were naked.",
  "Is it true that you (whatever you or the group suspects they do/did)?",
  "What do you really hope your parents never find out about?",
  "What have you done that people here would judge you most for doing?",
];
final List<String> juicyTruths = [
  "What is the biggest lie you have ever told?",
  "Have you ever made out with someone here?",
  "Have you ever cheated or been cheated on?",
  "What are your top three turn-ons?",
  "Who is the person you most regret kissing?",
  " Who was the last person you licked?",
  "What colour underwear are you wearing right now?",
  "Do you have any fetishes?",
  "What’s a secret you’ve never told anyone?",
  "What are your thoughts on polyamory?",
  "What’s your biggest fantasy?",
  "What was the most awkward romantic encounter you have had?",
  "Who is your crush?",
  "What is the naughtiest thing you’ve done in public?",
  "What is something that people think you would never be into, but you are?",
  "What’s the worst intimate experience you’ve ever had?",
  "Who would you like to kiss in this room?",
  "Where’s the weirdest place you’ve had sex?",
  "What’s an instant deal breaker in a potential love interest?",
  "What’s the worst date you’ve been on?",
  "Who’s the sexiest person here?",
  "What is your favourite thing that your boyfriend or girlfriend does?",
  "Describe your most recent romantic encounter in detail.",
  "What is the weirdest thing you have done for a boyfriend or girlfriend?",
  "Tell me something you don’t want me to know.",
  "What is something that you have never told anyone?",
];
